#!/usr/bin/env python
import sys,os


print """
install form. Select option:

  1 linux
  2 osx

"""

option=int(raw_input("option [1]:"))
if option==1:
  os.system('cp src/form form.exe ')
  os.system('chmod +x form.exe ')
elif option==2:
  os.system('cp src/form-darwing form.exe ')
  os.system('chmod +x form.exe ')
else:
  print 'option not available'
  sys.exit()





