#!/usr/bin/env python
import sys,os
cwd=os.getcwd()

os.chdir('qgraf')
os.system('./install')
os.chdir(cwd)

os.chdir('form')
os.system('./install')
os.chdir(cwd)

os.chdir('rambo')
os.system('make')
os.chdir(cwd)

#os.chdir('external')
#os.system('./install')
#os.chdir(cwd)
